CREATE TABLE PROFESSOR (
  Professor_ID int PRIMARY KEY,
  First_Name VARCHAR2(20) NOT NULL,
  Last_Name VARCHAR2(20) NOT NULL,
  email VARCHAR2(50) NOT NULL,
  dept VARCHAR2(10) NOT NULL
);

-- fetch 
SELECT * FROM PROFESSOR;